
num_set = set([0, 1, 2, 3, 4, 5])
print("Original set elements :",num_set)
print("\nRemove 4 from the said set:")
num_set.discard(4)
print(num_set)
print("\nRemove 5 from the said set:")
num_set.discard(5)
print(num_set)
print("\nRemove 2 from the said set:")
num_set.discard(2)
print(num_set)
print("\nRemove 7 from the said set:")
num_set.discard(7)
print("No element found :",num_set)
